
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - core.vedette.io
  resources:
  - interfaceclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.vedette.io
  resources:
  - interfaceclaims/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.vedette.io
  resources:
  - interfaceinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.vedette.io
  resources:
  - interfaceinstances/status
  verbs:
  - get
  - patch
  - update
